FROM python:3.9-slim

WORKDIR /app

# копирование файлов зависимостей
COPY requirements.txt requirements.txt

# устанавливаю зависимости
RUN pip install -r requirements.txt
RUN pip install flask-sqlalchemy flask-migrate psycopg2-binary redis Flask-Caching  prometheus-flask-exporter pytest

ENV SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/flask_db
ENV REDIS_HOST=redis

COPY . .
EXPOSE 5000
CMD ["pytest"]
