# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt requirements.txt

# Устанавливаем зависимости
RUN pip install -r requirements.txt
RUN pip install flask-sqlalchemy flask-migrate psycopg2-binary redis Flask-Caching pytest 

ENV SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/flask_db
ENV REDIS_HOST=redis
# Копируем все файлы приложения
COPY . .

# Открываем порт 5000 для Flask
EXPOSE 5000

# Команда для запуска тестов
CMD ["pytest"]
